workflows:
  ios-workflow:
    name: iOS IPA Build
    max_build_duration: 60

    environment:
      flutter: stable
      xcode: latest

    scripts:
      - name: Get dependencies
        script: |
          flutter pub get

      - name: Build IPA
        script: |
          flutter build ipa --release

      - name: Show build files
        script: |
          echo "Listing build directory"
          ls -R build/ios

    artifacts:
      - build/ios/ipa/*.ipa
      - build/ios/archive/**/*.ipa